// router
export const SET_ROUTERLIST = 'SET_ROUTERLIST'
export const SET_ROUTERANIMATION = 'SET_ROUTERANIMATION' 

// documentClick
export const SET_DOCUMENTCLICK = 'SET_DOCUMENTCLICK'

// selectZIndex
export const SET_SELECTZINDEX = 'SET_SELECTZINDEX'

// loading
export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

// msgTip
export const SET_MSGTIP = 'SET_MSGTIP'
export const SET_MSGTIPSTYLE = 'SET_MSGTIPSTYLE'
export const HIDE_MSGTIP = 'HIDE_MSGTIP'


export const SET_NEEDLOGIN = 'SET_NEEDLOGIN'

export const SET_LOANINDEXREFRESH = 'SET_LOANINDEXREFRESH'

export const SET_FUNCIDS = 'SET_FUNCIDS'

//
export const SET_CITY = 'SET_CITY'

export const SET_CARINFO = 'SET_CARINFO'
export const SET_CARCURRENT = 'SET_CARCURRENT'

export const SET_POLICYHISTORY = 'SET_POLICYHISTORY'

export const SET_INVOICERESULT = 'SET_INVOICERESULT'
export const SET_INVOICESUPPORT = 'SET_INVOICESUPPORT'

export const SET_PROVIDENTFUNDCITY = 'SET_PROVIDENTFUNDCITY'
export const SET_PROVIDENTFUNDRESULT = 'SET_PROVIDENTFUNDRESULT'

export const SET_CREDITCARDBILLSRESULT = 'SET_CREDITCARDBILLSRESULT'

export const SET_STUDENTSTATUSRESULT = 'SET_STUDENTSTATUSRESULT'

export const SET_BLACKLISTRESULT = 'SET_BLACKLISTRESULT'

export const SET_OPERATORSRESULT = 'SET_OPERATORSRESULT'

export const SET_USERID = 'SET_USERID'

export const SET_CHANNEL = 'SET_CHANNEL'

export const SET_ADMIN = 'SET_ADMIN'

export const SET_CARDPRICE = 'SET_CARDPRICE'

export const ADD_CARD = 'ADD_CARD'
export const EDIT_CARD = 'EDIT_CARD'
export const DELETE_CARD = 'DELETE_CARD'

export const SET_BAODANRESULT = 'SET_BAODANRESULT'
export const REMOVE_BAODANRESULT = 'REMOVE_BAODANRESULT'

export const SET_INDEXVIEWFORM = 'SET_INDEXVIEWFORM'
export const SET_COMPANYLIST = 'SET_COMPANYLIST'

export const SET_SEARCHHISTORY = 'SET_SEARCHHISTORY'
export const SET_SEARCHHISTORYFORM = 'SET_SEARCHHISTORYFORM'
export const SET_SEARCHHISTORYCURRENTPAGE = 'SET_SEARCHHISTORYCURRENTPAGE'

export const SET_UPDATEDASHBOARD = 'SET_UPDATEDASHBOARD'
export const SET_DASHBOARD = 'SET_DASHBOARD'

export const SET_REQUESTPARAMS = 'SET_REQUESTPARAMS'
export const SET_SESSIONID = 'SET_REQUESTPARAMS'
export const SET_AUTHTYPE = 'SET_AUTHTYPE'
